#!/usr/bin/env nu
# tools/opgen/main.nu — generates the operator artifacts for the two
# compilers and the docs from process/spec/operators.yaml (the single source
# of truth for every operator: symbol, tier, binding powers, associativity,
# operand/result types, description).
#
# Emits:
#   src/operators_gen.odin    TIER_* + BINARY_OPERATORS + PRECEDENCE_TABLE
#   selfhost/src/operators.dva the `bin_info` table
#   GRAMMAR.md                the §1.6 operators/precedence table (between
#                             markers)
#
# Usage:
#   nu tools/opgen/main.nu            # write the artifacts in place
#   nu tools/opgen/main.nu --check    # verify the artifacts are in sync
#                                     # (exit 1 when out of date)
#
# build.sh runs the generator; run_tests.sh runs --check.

const SRC = "process/spec/operators.yaml"
const DOC_MARKER_BEGIN = "<!-- BEGIN operators.yaml -->"
const DOC_MARKER_END = "<!-- END operators.yaml -->"

def root [] {
    ($env.FILE_PWD | path dirname | path dirname)
}

def assoc_str [a] {
    if $a == "right" {
        ".RightAssoc"
    } else {
        ".LeftAssoc"
    }
}

def result_str [r] {
    if $r == "int" {
        ".Int"
    } else if $r == "comparison" {
        ".Comparison"
    } else if $r == "like-lhs" {
        ".LikeLHS"
    } else if $r == "feed" {
        ".Feed"
    } else {
        ""
    }
}

# -------- Odin: src/operators_gen.odin -------------------------------------

def gen_odin [] {
    let d = open ((root) | path join "process/spec/operators.yaml")

    let tier_consts = ($d.tiers | each { |t|
        let name = $"TIER_($t.const)"
        let pad = 13 - ($name | str length)
        $name + (0..<$pad | each { " " } | str join "") + " :: " + (($t.number - 1) | into string)
    } | str join "\n")

    let binops = ($d.operators | where kind != null | each { |o|
        let t = ($d.tiers | where name == $o.tier | first)
        let sl = if $t.same_line { ", same_line = true" } else { "" }
        $"    {token = \"($o.symbol)\", tier = TIER_($t.const), kind = .($o.kind)($sl)},"
    } | str join "\n")

    let rows = ($d.tiers | each { |t|
        let ops = ($d.operators | where tier == $t.name | get symbol | str join "  ")
        let result = (result_str $t.result)
        let result_line = if $result == "" { "" } else { $"\n\t\tresult = ($result)," }
        let same_line = if $t.same_line { "\n\t\tsame_line = true," } else { "" }
        $"\t{\n\t\tnumber = ($t.number),\n\t\tname = \"($t.name)\",\n\t\tops = \"($ops)\",\n\t\tparse_fn = \"($t.parse_fn)\",\n\t\tlhs_bp = ($t.lbp),\n\t\trhs_bp = ($t.rbp),\n\t\tassoc = (assoc_str $t.assoc),($result_line)($same_line)\n\t},"
    } | str join "\n")

    [
        "// Code generated by tools/opgen/main.nu from process/spec/operators.yaml — DO NOT EDIT.",
        "// Edit the YAML and rerun the generator; build.sh does it automatically.",
        "",
        "package main",
        "",
        "// TIER_* indexes into PRECEDENCE_TABLE; binary_tier_of_op uses them.",
        $tier_consts,
        "",
        "// A binary operator token and its tier + BinaryOp kind. Binary operators are",
        "// the Pratt-loop rows of PRECEDENCE_TABLE (tiers 6-14); everything else is",
        "// owned by a dedicated parse function.",
        "BinaryOperator :: struct {",
        "\ttoken:     string,",
        "\ttier:      int,",
        "\tkind:      BinaryOp,",
        "\tsame_line: bool,",
        "}",
        "",
        "// Maps each binary operator token to its tier and BinaryOp kind.",
        "BINARY_OPERATORS := []BinaryOperator{",
        $binops,
        "}",
        "",
        "// PRECEDENCE_TABLE drives parser_parse_expr_bp (src/parser.odin). Each row is",
        "// one operator tier; lhs_bp/rhs_bp are the binding powers the Pratt loop",
        "// consults, assoc picks left/right association, result is the val_type the",
        "// loop stamps on the Binary nodes it builds.",
        "PRECEDENCE_TABLE := []Tier{",
        $rows,
        "}",
        "",
    ] | str join "\n"
}

# -------- Selfhost: operators.dva -------------------------------------------

def gen_operators_file [] {
    let d = open ((root) | path join "process/spec/operators.yaml")
    let lines = ($d.operators | where kind_self != null | each { |o|
        let t = ($d.tiers | where name == $o.tier | first)
        let sl = if $t.same_line { "<+>" } else { "<->" }
        let op = $"ast::BinaryOp\(($o.kind_self)\)"
        let info = $"BinOpInfo\(\(($t.lbp), ($t.rbp), ($op), ($sl)\)\)"
        $"      [\"($o.symbol)\"]  <+ ($info) ->"
    } | str join "\n")
    [
        "// selfhost/src/operators.dva — the operator table, ported from",
        "// src/operators_gen.odin. GENERATED by tools/opgen/main.nu from",
        "// process/spec/operators.yaml — DO NOT EDIT; edit the YAML and rerun",
        "// the generator (build.sh does it).",
        "",
        "#use \"ast\"",
        "",
        "#type BinOpInfo (lbp: Int, rbp: Int, op: ast::BinaryOp, same_line: <>)",
        "",
        "// Returns the binary operator for a token's text, or none. Binding",
        "// powers follow process/spec/operators.yaml (tier number * 10). The",
        "// comparison tier is same-line: only one comparison may chain",
        "// operators across a newline.",
        "bin_info: String => < BinOpInfo | >",
        "bin_info = text =>",
        "   text",
        $lines,
        "      | <-->",
        "",
    ] | str join "\n"
}

# -------- Docs: GRAMMAR.md §1.6 --------------------------------------------

def gen_doc_block [] {
    let d = open ((root) | path join "process/spec/operators.yaml")
    let rows = ($d.tiers | each { |t|
        let ops = ($d.operators | where tier == $t.name | get symbol | each { |s| $"`($s)`" } | str join " ")
        let assoc = if $t.assoc == "right" { "right" } else { "left" }
        let same = if $t.same_line { ", same-line" } else { "" }
        $"| ($t.name) | ($t.lbp) | ($t.rbp) | ($ops) | ($assoc)($same) |"
    } | str join "\n")
    [
        $DOC_MARKER_BEGIN,
        "| Tier | LBP | RBP | Operators | Associativity |",
        "|---|---|---|---|---|",
        $rows,
        "",
        $DOC_MARKER_END,
    ] | str join "\n"
}

# -------- helpers ----------------------------------------------------------

def replace_block [content: string, marker_begin: string, marker_end: string, replacement: string] {
    let start = ($content | str index-of $marker_begin)
    let end = ($content | str index-of $marker_end)
    if $start < 0 or $end < 0 {
        error make { msg: $"markers not found: ($marker_begin) / ($marker_end)" }
    }
    # nushell str substring ranges are inclusive; use exclusive ranges so the
    # marker text itself is removed and replaced.
    let before = ($content | str substring 0..<$start)
    let after_start = $end + ($marker_end | str length)
    let after = ($content | str substring $after_start..)
    $before + $replacement + $after
}

def artifact_odin [] {
    gen_odin
}

def artifact_operators [] {
    gen_operators_file
}

def artifact_doc [content: string] {
    replace_block $content $DOC_MARKER_BEGIN $DOC_MARKER_END (gen_doc_block)
}

# -------- main -------------------------------------------------------------

def main [--check] {
    let root_dir = (root)
    let odin_path = if ("src/operators_gen.odin" | path exists) {
        $root_dir | path join "src/operators_gen.odin"
    } else {
        $root_dir | path join "process/archive/odin/src/operators_gen.odin"
    }
    let operators_path = ($root_dir | path join "src/operators.dva")
    let doc_path = ($root_dir | path join "GRAMMAR.md")

    let odin = (artifact_odin)
    let operators_new = (artifact_operators)
    let doc_new = (artifact_doc (open --raw $doc_path))

    if $check {
        let odin_ok = if ($odin_path | path exists) {
            $odin == (open --raw $odin_path)
        } else {
            true
        }
        let operators_ok = ($operators_new == (open --raw $operators_path))
        let doc_new_raw = (open --raw $doc_path)
        let doc_ok = ($doc_new == $doc_new_raw)
        if not $odin_ok {
            print "operators.yaml: src/operators_gen.odin is out of sync — run 'nu tools/opgen/main.nu'."
        }
        if not $operators_ok {
            print "operators.yaml: src/operators.dva is out of sync — run 'nu tools/opgen/main.nu'."
        }
        if not $doc_ok {
            print "operators.yaml: GRAMMAR.md operator table is out of sync — run 'nu tools/opgen/main.nu'."
        }
        if (not $odin_ok) or (not $operators_ok) or (not $doc_ok) {
            exit 1
        }
        print "operators.yaml: all artifacts in sync."
    } else {
        if ($odin_path | path exists) {
            $odin | save -f $odin_path
        }
        $operators_new | save -f $operators_path
        $doc_new | save -f $doc_path
        print "operators.yaml: regenerated src/operators.dva, GRAMMAR.md."
    }
}