#!/usr/bin/env nu
# tools/opgen/main.nu — generates the operator artifacts from operators.yaml
# (the single source of truth for every operator: symbol, tier, binding powers,
# associativity, operand/result types, description).
#
# Emits:
#   src/operators.dva the `bin_info` table
#   GRAMMAR.md       the §1.6 operators/precedence table (between markers)
#
# Usage:
#   nu tools/opgen/main.nu            # write the artifacts in place
#   nu tools/opgen/main.nu --check    # verify the artifacts are in sync
#                                     # (exit 1 when out of date)

const SRC = "operators.yaml"
const DOC_MARKER_BEGIN = "<!-- BEGIN operators.yaml -->"
const DOC_MARKER_END = "<!-- END operators.yaml -->"

def root [] {
    ($env.FILE_PWD | path dirname | path dirname)
}

# -------- Selfhost: operators.dva -------------------------------------------

def gen_operators_file [] {
    let d = open ((root) | path join "operators.yaml")
    let lines = ($d.operators | where kind_self != null | each { |o|
        let t = ($d.tiers | where name == $o.tier | first)
        let sl = if $t.same_line { "<+>" } else { "<->" }
        let op = $"ast::BinaryOp\(($o.kind_self)\)"
        let info = $"BinOpInfo\(\(($t.lbp), ($t.rbp), ($op), ($sl)\)\)"
        $"      [\"($o.symbol)\"]  <+ ($info) +>"
    } | str join "\n")
    [
        "// src/operators.dva — the operator table. GENERATED by tools/opgen/main.nu",
        "// from operators.yaml — DO NOT EDIT; edit the YAML and rerun the generator (build.sh does it).",
        "",
        "#use \"ast\"",
        "",
        "#public",
        "",
        "#type BinOpInfo (lbp: Int, rbp: Int, op: ast::BinaryOp, same_line: <>)",
        "",
        "// Returns the binary operator for a token's text, or none. Binding",
        "// powers follow operators.yaml (tier number * 10). The",
        "// comparison tier is same-line: only one comparison may chain",
        "// operators across a newline.",
        "bin_info: String => < BinOpInfo | >",
        "bin_info = text =>",
        "   text",
        $lines,
        "      | <-->",
        "",
    ] | str join "\n"
}

# -------- Docs: GRAMMAR.md §1.6 --------------------------------------------

def gen_doc_block [] {
    let d = open ((root) | path join "operators.yaml")
    let rows = ($d.tiers | each { |t|
        let ops = ($d.operators | where tier == $t.name | get symbol | each { |s| $"`($s)`" } | str join " ")
        let assoc = if $t.assoc == "right" { "right" } else { "left" }
        let same = if $t.same_line { ", same-line" } else { "" }
        $"| ($t.name) | ($t.lbp) | ($t.rbp) | ($ops) | ($assoc)($same) |"
    } | str join "\n")
    [
        $DOC_MARKER_BEGIN,
        "| Tier | LBP | RBP | Operators | Associativity |",
        "|---|---|---|---|---|",
        $rows,
        "",
        $DOC_MARKER_END,
    ] | str join "\n"
}

# -------- helpers ----------------------------------------------------------

def replace_block [content: string, marker_begin: string, marker_end: string, replacement: string] {
    let start = ($content | str index-of $marker_begin)
    let end = ($content | str index-of $marker_end)
    if $start < 0 or $end < 0 {
        error make { msg: $"markers not found: ($marker_begin) / ($marker_end)" }
    }
    let before = ($content | str substring 0..<$start)
    let after_start = $end + ($marker_end | str length)
    let after = ($content | str substring $after_start..)
    $before + $replacement + $after
}

def artifact_operators [] {
    gen_operators_file
}

def artifact_doc [content: string] {
    replace_block $content $DOC_MARKER_BEGIN $DOC_MARKER_END (gen_doc_block)
}

# -------- main -------------------------------------------------------------

def main [--check] {
    let root_dir = (root)
    let operators_path = ($root_dir | path join "src/operators.dva")
    let doc_path = ($root_dir | path join "GRAMMAR.md")

    let operators_new = (artifact_operators)
    let doc_new = (artifact_doc (open --raw $doc_path))

    if $check {
        let operators_ok = (($operators_new | str trim) == ((open --raw $operators_path) | str trim))
        let doc_new_raw = (open --raw $doc_path)
        let doc_ok = (($doc_new | str trim) == ($doc_new_raw | str trim))
        if not $operators_ok {
            print "operators.yaml: src/operators.dva is out of sync — run 'nu tools/opgen/main.nu'."
        }
        if not $doc_ok {
            print "operators.yaml: GRAMMAR.md operator table is out of sync — run 'nu tools/opgen/main.nu'."
        }
        if (not $operators_ok) or (not $doc_ok) {
            exit 1
        }
        print "operators.yaml: all artifacts in sync."
    } else {
        $operators_new | save -f $operators_path
        $doc_new | save -f $doc_path
        print "operators.yaml: regenerated src/operators.dva, GRAMMAR.md."
    }
}