#!/usr/bin/env nu
# tools/gen_version.nu — generates src/version.dva from VERSION and git commit hash

def root [] {
    $env.FILE_PWD | path dirname
}

def main [] {
    let repo_root = (root)
    let version_file = ($repo_root | path join "VERSION")
    let version = if ($version_file | path exists) {
        open --raw $version_file | str trim
    } else {
        "1.0.0"
    }

    let commit = try {
        cd $repo_root
        git rev-parse --short HEAD | str trim
    } catch {
        "unknown"
    }

    let target = ($repo_root | path join "src/version.dva")
    let content = $"// src/version.dva — generated by tools/gen_version.nu \(do not edit manually\)\n#public\n   VERSION = \"($version)\"\n   COMMIT_HASH = \"($commit)\"\n"

    let existing = if ($target | path exists) {
        open --raw $target
    } else {
        ""
    }

    if $existing != $content {
        $content | save --raw -f $target
        print $"Generated ($target): version=($version), commit=($commit)"
    }
}
