#!/usr/bin/env nu
# tools/gendeps.nu — generates the Makefile module-dependency fragment.
#
# For every compiled source, follows `#use` directives transitively and emits
#   build/obj/<module>.o: <every .dva file it can reach>
# so editing any imported module (directly or through a chain of imports)
# rebuilds the dependent objects. Resolution mirrors `resolve_module` in
# src/edva.dva: <importer dir>, then its parent dir, then std/ — file first
# (`<name>.dva`), a same-named directory as fallback (all its .dva files).
#
# Object naming mirrors the Makefile pattern rules: the first path segment is
# dropped (src/codegen/expr.dva -> build/obj/codegen/expr.o,
# std/str.dva -> build/obj/str.o).
#
# Usage (run by make; paths are relative to the repo root):
#   nu tools/gendeps.nu build/deps.mk src/parser.dva std/str.dva ...

const USE_RE = '^\s*#use(?:\([^)]*\))?\s+"?(?<m>[^"\s]+)"?'

def root [] {
    $env.FILE_PWD | path dirname
}

# Repo-relative, normalized form of a path (collapses `..` segments).
def rel [p: string] {
    $p | path expand --no-symlink | path relative-to (root)
}

def dir_sources [dir: string] {
    glob ($dir | path join "*.dva") | each {|f| rel $f } | sort
}

# The .dva files a `#use <mod>` from a file in `base` resolves to.
def resolve [base: string, mod: string] {
    let parent = ($base | path dirname)
    mut bases = [$base]
    if $parent != "" and $parent != "." { $bases = ($bases | append $parent) }
    $bases = ($bases | append "std")
    for b in $bases {
        let f = ($b | path join $"($mod).dva")
        if ($f | path type) == "file" { return [(rel $f)] }
        let d = ($b | path join $mod)
        if ($d | path type) == "dir" { return (dir_sources $d) }
    }
    []
}

def direct_deps [file: string] {
    let base = ($file | path dirname)
    open --raw $file | lines | parse --regex $USE_RE | get m | uniq
    | each {|m|
        let r = (resolve $base $m)
        if ($r | is-empty) {
            print -e $"gendeps: ($file): cannot resolve '#use ($m)' — skipped"
        }
        $r
    }
    | flatten
}

def closure [file: string] {
    mut seen = []
    mut todo = [$file]
    while not ($todo | is-empty) {
        let f = ($todo | first)
        $todo = ($todo | skip 1)
        if $f in $seen { continue }
        $seen = ($seen | append $f)
        $todo = ($todo | append (direct_deps $f))
    }
    $seen | where {|x| $x != $file } | sort
}

def obj_for [src: string] {
    let parts = ($src | path split | skip 1)
    let stem = ($parts | path join | str replace --regex '\.dva$' '.o')
    $"build/obj/($stem)"
}

def rule [target: string, deps: list<string>] {
    if ($deps | is-empty) { return $"($target):" }
    let body = ($deps | str join " \\\n  ")
    $"($target): \\\n  ($body)"
}

def main [out: string, ...sources: string] {
    cd (root)
    let srcs = ($sources | each {|s| rel $s })
    let rules = ($srcs | each {|s| { obj: (obj_for $s), deps: (closure $s) } })
    let all_deps = ($rules | get deps | flatten | uniq | sort)
    let text = ([
        "# build/deps.mk — GENERATED by tools/gendeps.nu from `#use` directives."
        "# DO NOT EDIT; make regenerates it whenever a .dva source changes."
        ""
        ...($rules | each {|r| rule $r.obj $r.deps })
        ""
        "# Empty rules so a deleted/renamed module does not break the build."
        ...($all_deps | each {|d| $"($d):" })
        ""
    ] | str join "\n")
    mkdir ($out | path dirname)
    $text | save -f $out
}
